=== acit4850xml/acit4850lab7/data/scheduleschema.xsd
<?xml version="1.0"?>


<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <!--Data type for courses-->
    <xs:simpleType name="Tcourses">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A][C][I][T]\d{4}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!--Datatype for possible times-->
    <xs:simpleType name="Ttime">
        <xs:restriction base="xs:string">
            <xs:enumeration value="1"/>
            <xs:enumeration value="2"/>
            <xs:enumeration value="3"/>
            <xs:enumeration value="4"/>
            <xs:enumeration value="5"/>
            <xs:enumeration value="6"/>
            <xs:enumeration value="7"/>
            <xs:enumeration value="8"/>
            <xs:enumeration value="9"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    <!--Data Type for classtype -->
    <xs:simpleType name="Tclasstype">
        <xs:restriction base="xs:string">
            <xs:enumeration value="lab"/>
            <xs:enumeration value="lecture"/>
            <xs:enumeration value="tutorial"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!-- Data Type for possible days of the week -->
    <xs:simpleType name="Tdays">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Monday"/>
            <xs:enumeration value="Tuesday"/>
            <xs:enumeration value="Wednesday"/>
            <xs:enumeration value="Thursday"/>
            <xs:enumeration value="Friday"/>
        </xs:restriction>
    </xs:simpleType>

    <!--Data Type for rooms -->
    <xs:simpleType name="Troom">
        <xs:restriction base="xs:string">
            <xs:pattern value="\w{2}\d{1,2}[-]\d+"/>
        </xs:restriction>
    </xs:simpleType>

    <!--Data Type for Instructor Names -->
    <xs:simpleType name="Tinstructor">
        <xs:restriction base="xs:string">
            <xs:pattern value="\w+\s\w+"/>
        </xs:restriction>
    </xs:simpleType>
    
    <!--root element timetable that contains the 3 facets-->
    <xs:element name="timetable">
        <xs:complexType>
            <xs:sequence>
                
                <!--timeslot facets -->
                <xs:element name="timeslots" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="course" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="Troom" name="room"/>
                                        <xs:element type="Tinstructor" name="instructor"/>
                                        <xs:element name="classtype">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute type="Tclasstype" name="type" use="optional"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="day">
                                            <xs:complexType>
                                                <xs:simpleContent>
                                                    <xs:extension base="xs:string">
                                                        <xs:attribute type="Tdays" name="type" use="optional"/>
                                                    </xs:extension>
                                                </xs:simpleContent>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute type="Tcourses" name="course" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="Ttime" name="type" use="optional"/>
                    </xs:complexType>
                </xs:element>
                
              
                
                
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== acit4850xml/acit4850lab7/data/schedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!--<!DOCTYPE timetable SYSTEM 'schedule.dtd'>-->

<timetable xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="scheduleschema.xsd">
    
    <!--
    timeslot facet
    -->
    
    <timeslots type="1">
        <course course="ACIT4660">
            <room>SW9-206</room>
            <instructor>Stephen Fabiszewski</instructor>
            <classtype type="lecture"/>
            <day type="Friday"/>
        </course>
    </timeslots>
    
    <timeslots type="2">
        <course course="ACIT4660">
            <room>SW9-206</room>
            <instructor>Stephen Fabiszewski</instructor>
            <classtype type="lecture"/>
            <day type="Friday"/>
        </course>
        
        <course course="ACIT4910">
            <room>SW5-1840</room>
            <instructor>Richard Chau</instructor>
            <classtype type="lecture"/>
            <day type="Thursday"/>
        </course>
    </timeslots>
    
    <timeslots type="3">
        <course course="ACIT4620">
            <room>SE12-306</room>
            <instructor>Bethany Edmunds</instructor>    
            <classtype type="lab"/>
            <day type="Tuesday"/>
        </course>
        
        <course course="ACIT4660">
            <room>SE12-306</room>
            <instructor>Stephen Fabiszewski</instructor>
            <classtype type="lab"/>
            <day type="Wednesday"/>
        </course>
        
        <course course="ACIT4850">
            <room>SE12-320</room>
            <instructor>Jim Parry</instructor>
            <classtype type="lab"/>
            <day type="Thursday"/>
        </course>
    </timeslots>
    
    <timeslots type="4">
        <course course="ACIT4620">
            <room>SE12-306</room>
            <instructor>Bethany Edmunds</instructor>
            <classtype type="lab"/>
            <day type="Tuesday"/>
        </course>
        
        <course course="ACIT4660">
            <room>SE12-306</room>
            <instructor>Stephen Fabiszewski</instructor>
            <classtype type="lab"/>
            <day type="Wednesday"/>
        </course>
        
        <course course="ACIT4850">
            <room>SE12-320</room>
            <instructor>Jim Parry</instructor>
            <classtype type="lab"/>
            <day type="Thursday"/>
        </course>
    </timeslots>

    <timeslots type="5">
        <course course="ACIT4620">
            <room>SW1-2009</room>
            <instructor>Bethany Edmunds</instructor>
            <classtype type="lecture"/>
            <day type="Monday"/>
        </course>
        
        <course course="ACIT4650">
            <room>SW9-206</room>
            <instructor>Medhat Elmasry</instructor>
            <classtype type="lecture"/>
            <day type="Tuesday"/>
        </course>
        
        <course course="ACIT4850">
            <room>SW3-1750</room>
            <instructor>Jim Parry</instructor>
            <classtype type="lecture"/>
            <day type="Wednesday"/>
        </course>
       
    </timeslots>
    
    <timeslots type="6">
        <course course="ACIT4770">
            <room>SE12-306</room>
            <instructor>Trevor Lord</instructor>
            <classtype type="tutorial"/>
            <day type="Monday"/>
        </course>
        
        <course course="ACIT4650">
            <room>SE12-306</room>
            <instructor>Medhat Elmasry</instructor>
            <classtype type="lab"/>
            <day type="Tuesday"/>
        </course>
        
        <course course="ACIT4850">
            <room>SW3-1750</room>
            <instructor>Jim Parry</instructor>
            <classtype type="lecture"/>
            <day type="Wednesday"/>
        </course>
        
        <course course="ACIT4910">
            <room>SE12-306</room>
            <instructor>Richard Chau</instructor>
            <classtype type="lab"/>
            <day type="Thursday"/>
        </course>
    </timeslots>
    
    <timeslots type="7">
        <course course="ACIT4770">
            <room>SE12-306</room>
            <instructor>Trevor Lord</instructor>
            <classtype type="tutorial"/>
            <day type="Monday"/>
        </course>
        
        <course course="ACIT4650">
            <room>SE12-306</room>
            <instructor>Medhat Elmasry</instructor>
            <classtype type="lab"/>
            <day type="Tuesday"/>
        </course>
        
        <course course="ACIT4910">
            <room>SE12-306</room>
            <instructor>Richard Chau</instructor>
            <classtype type="lab"/>
            <day type="Thursday"/>
        </course>
    </timeslots>
    
    
    <timeslots type="8">
        <course course="ACIT4910">
            <room>SW9-206</room>
            <instructor>Richard Chau</instructor>
            <classtype type="lecture"/>
            <day type="Monday"/>
        </course>
        
        <course course="ACIT4620">
            <room>SW3-3615</room>
            <instructor>Bethany Edmunds</instructor>
            <classtype type="lecture"/>
            <day type="Tuesday"/>
        </course>
        
    </timeslots>
    
    <timeslots type="9">
        <course course="ACIT4650">
            <room>SE6-205</room>
            <instructor>Medhat Elmasry</instructor>
            <classtype type="lecture"/>
            <day type="Monday"/>
        </course>
    </timeslots>
   
    
    <!--
    courses facet
    -->
    
    
    <courses course="ACIT4620">
            <timeslot type = "1"/>
            <day type="Friday"/>
            <room>SW9-206</room>
            <instructor>Stephen Fabiszewski</instructor>
            <classtype type="lecture"/>
    </courses>
    
        
    <courses course="ACIT4620">
        <timeslot type = "3"/>
        <day type="Tuesday"/>
        <room>SE12-306</room>
        <instructor>Bethany Edmunds</instructor>
        <classtype type="lab"/>
    </courses>
    
    <courses course="ACIT4620">
        <timeslot type = "4"/>
        <day type="Tuesday"/>
        <room>SE12-306</room>
        <instructor>Bethany Edmunds</instructor>
        <classtype type="lab"/>
    </courses>
        
    <courses course="ACIT4650">
        <timeslot type = "5"/>
        <day type="Monday"/>
        <room>SW9-206</room>
        <instructor>Medhat Elmasry</instructor>
        <classtype type="lecture"/>
    </courses>
        
    <courses course="ACIT4650">
        <timeslot type = "9"/>
        <day type="Tuesday"/>
        <room>SW9-206</room>
        <instructor>Medhat Elmasry</instructor>
        <classtype type="lecture"/>
    </courses>
        
    <courses course="ACIT4650">
        <timeslot type = "6"/>
        <day type="Tuesday"/>
        <room>SE12-306</room>
        <instructor>Farnaz Dargahi</instructor>
        <classtype type="lab"/>
    </courses>
    
    <courses course="ACIT4650">
        <timeslot type = "7"/>
        <day type="Tuesday"/>
        <room>SE12-306</room>
        <instructor>Farnaz Dargahi</instructor>
        <classtype type="lab"/>
    </courses>
        
    <courses course="ACIT4660">
        <timeslot type = "1"/>
        <day type="Friday"/>
        <room>SW9-206</room>
        <instructor>Steve Fabiszewski</instructor>
        <classtype type="lecture"/>
    </courses>
    
    <courses course="ACIT4660">
        <timeslot type = "2"/>
        <day type="Friday"/>
        <room>SW9-206</room>
        <instructor>Steve Fabiszewski</instructor>
        <classtype type="lecture"/>
    </courses>
        
    <courses course="ACIT4660">
        <timeslot type = "3"/>
        <day type="Wednesday"/>
        <room>SE12-306</room>
        <instructor>Steve Fabiszewski</instructor>
        <classtype type="lab"/>
    </courses>
    
    <courses course="ACIT4660">
        <timeslot type = "4"/>
        <day type="Wednesday"/>
        <room>SE12-306</room>
        <instructor>Steve Fabiszewski</instructor>
        <classtype type="lab"/>
    </courses>
        
    <courses course="ACIT4770">
        <timeslot type = "6"/>
        <day type="Monday"/>
        <room>SE12-306</room>
        <instructor>Trevor Lord</instructor>
        <classtype type="tutorial"/>
    </courses>
    
    <courses course="ACIT4770">
        <timeslot type = "7"/>
        <day type="Monday"/>
        <room>SE12-306</room>
        <instructor>Trevor Lord</instructor>
        <classtype type="tutorial"/>
    </courses>
        
    <courses course="ACIT4850">
        <timeslot type = "5"/>
        <day type="Wednesday"/>
        <room>SW3-1750</room>
        <instructor>Jim Parry</instructor>
        <classtype type="lecture"/>
    </courses>
    
    <courses course="ACIT4850">
        <timeslot type = "6"/>
        <day type="Wednesday"/>
        <room>SW3-1750</room>
        <instructor>Jim Parry</instructor>
        <classtype type="lecture"/>
    </courses>
        
    <courses course="ACIT4850">
        <timeslot type = "3"/>
        <day type="Thursday"/>
        <room>SE12-320</room>
        <instructor>Jim Parry</instructor>
        <classtype type="lab"/>
    </courses>
        
    <courses course="ACIT4850">
        <timeslot type = "4"/>
        <day type="Thursday"/>
        <room>SE12-320</room>
        <instructor>Jim Parry</instructor>
        <classtype type="lab"/>
    </courses>    
    
    <courses course="ACIT4910">
        <timeslot type = "2"/>
        <day type="Thursday"/>
        <room>SW5-1840</room>
        <instructor>Richard Chau</instructor>
        <classtype type="lecture"/>
    </courses>
    
    <courses course="ACIT4910">
        <timeslot type = "7"/>
        <day type="Thursday"/>
        <room>SE12-306</room>
        <instructor>Richard Chau</instructor>
        <classtype type="lab"/>
